version: "3.9"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./web/:/var/www/html
      - /var/www/html/node_modules
    ports:
      - 3000:80

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./api/:/var/www/html
      - /var/www/html/vendor
    ports:
      - 3001:80

volumes:
  web:
  api:

networks:
  internal:
    driver: bridge
